# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_birthdah',
            new_name='student_birthday',
        ),
    ]
