# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-09 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_id', models.CharField(max_length=200)),
                ('Food_name', models.CharField(max_length=200)),
                ('Food_cost', models.IntegerField(default=0)),
                ('Food_amount', models.IntegerField(default=0)),
                ('Food_season', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_id', models.CharField(max_length=200)),
                ('Member_name', models.CharField(max_length=200)),
                ('Member_email', models.CharField(max_length=200)),
                ('Member_password', models.CharField(max_length=200)),
                ('Member_phone', models.CharField(max_length=200)),
                ('Member_address', models.CharField(max_length=200)),
            ],
        ),
    ]
