# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-09 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_id', models.CharField(max_length=200)),
                ('List_time', models.DateTimeField(verbose_name='date published')),
                ('List_content', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juice.Member')),
            ],
        ),
    ]
