# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-25 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0002_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='List_content',
            new_name='List_content1',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='List_id',
            new_name='List_content2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Member_id',
            new_name='Mmeber_account',
        ),
        migrations.AddField(
            model_name='list',
            name='List_content3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
