# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-01 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0005_auto_20170601_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='customer',
            field=models.IntegerField(default=0),
        ),
    ]
