# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-05 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0006_auto_20170601_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='List_time',
            field=models.CharField(max_length=250),
        ),
    ]
